function [scenario, egoVehicle, egoVehicle1] = HighwayScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [159.05 -0.87 0;
    -150.45 -0.87 0];
laneSpecification = lanespec(3);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-147.71 -0.78 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car 1');

% Add the non-ego actors
egoVehicle1 = vehicle(scenario, ...
    'ClassID', 2, ...
    'Position', [-136.74 -0.78 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car2');

vehicle(scenario, ...
    'ClassID', 3, ...
    'Position', [-131.63 2.61 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car3');

vehicle(scenario, ...
    'ClassID', 4, ...
    'Position', [-127.31 -4.51 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car4');

vehicle(scenario, ...
    'ClassID', 5, ...
    'Position', [-129.29 -0.68 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car5');

